services:
  # caddy:
  #   image: caddy:latest
  #   container_name: caddy
  #   restart: always
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #   networks:
  #     - rocco
  #   ports:
  #     - 80:80
  #     - 443:443
  
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - rocco:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocco
    networks:
      - rocco
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - rocco:/data
    networks:
      - rocco
    ports:
      - 6379:6379

  # api:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.api
  #   container_name: rocco-api
  #   restart: always
  #   volumes:
  #     - .:/app
  #   networks:
  #     - rocco
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - postgres
  #     - redis

  # web:
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile.web
  #   container_name: rocco-web
  #   restart: always
  #   volumes:
  #     - .:/app
  #     - ./apps/web/nginx.conf:/etc/nginx/nginx.conf
  #   networks:
  #     - rocco
  #   ports:
  #     - 8080:80
  #   depends_on:
  #     - api

networks:
  rocco:
    driver: bridge

volumes:
  rocco:
