FROM node:16-alpine as base

LABEL version="0.0.1"
LABEL name="rocco-web"
LABEL description="rocco web application"
LABEL maintainer="Chase Ponti <cj@ponti.io>"

ENV PNPM_HOME="/root/.local/share/pnpm"
ENV PATH="${PATH}:${PNPM_HOME}"
RUN npm install --global pnpm@7.29.1
RUN apk add --no-cache libc6-compat
RUN apk update && apk add bash

# Add the Turbo CLI
RUN pnpm add -g turbo

# ------------------------------------------------------------------------------
FROM base AS builder

WORKDIR /app

COPY . .

RUN turbo prune --scope=rocco-web --docker

# ------------------------------------------------------------------------------
# Copy the lockfile and package.json files of the isolated subworkspace
FROM base AS installer

WORKDIR /app

# Copy the lockfile, package files, and of the isolated subworkspace
COPY --from=builder /app/out/json/ /app/
COPY --from=builder /app/out/pnpm-lock.yaml /app/pnpm-lock.yaml
COPY --from=builder /app/out/full/ /app/

# Install dependencies
RUN pnpm install --frozen-lockfile --prefer-frozen-lockfile --ignore-scripts

# Set default node environment to production
ARG NODE_ENV=production
ARG VITE_API_URL

# Copy node environment to the container
ENV NODE_ENV=${NODE_ENV}
ENV VITE_API_URL=${VITE_API_URL}

# Build the app
RUN turbo run build --filter=rocco-web

# ------------------------------------------------------------------------------
# Set up a lightweight web server to serve the built app
FROM nginx:alpine as release

# Copy the built app to the Nginx public directory
COPY --from=installer /app/apps/web/build /usr/share/nginx/html

# end