services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - rocco:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rocco
    networks:
      - rocco
    ports:
      - 5433:5432

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    volumes:
      - rocco:/data
    networks:
      - rocco
    ports:
      - 6379:6379

networks:
  rocco:
    driver: bridge

volumes:
  rocco:
