CREATE TABLE "covid_data" (
	"id" serial PRIMARY KEY NOT NULL,
	"iso_code" text,
	"continent" text,
	"location" text,
	"date" text,
	"total_cases" real,
	"new_cases" real,
	"new_cases_smoothed" real,
	"total_deaths" real,
	"new_deaths" real,
	"new_deaths_smoothed" real,
	"total_cases_per_million" real,
	"new_cases_per_million" real,
	"new_cases_smoothed_per_million" real,
	"total_deaths_per_million" real,
	"new_deaths_per_million" real,
	"new_deaths_smoothed_per_million" real,
	"reproduction_rate" real,
	"icu_patients" real,
	"icu_patients_per_million" real,
	"hosp_patients" real,
	"hosp_patients_per_million" real,
	"weekly_icu_admissions" real,
	"weekly_icu_admissions_per_million" real,
	"weekly_hosp_admissions" real,
	"weekly_hosp_admissions_per_million" real,
	"total_tests" real,
	"new_tests" real,
	"total_tests_per_thousand" real,
	"new_tests_per_thousand" real,
	"new_tests_smoothed" real,
	"new_tests_smoothed_per_thousand" real,
	"positive_rate" real,
	"tests_per_case" real,
	"tests_units" text,
	"total_vaccinations" real,
	"people_vaccinated" real,
	"people_fully_vaccinated" real,
	"total_boosters" real,
	"new_vaccinations" real,
	"new_vaccinations_smoothed" real,
	"total_vaccinations_per_hundred" real,
	"people_vaccinated_per_hundred" real,
	"people_fully_vaccinated_per_hundred" real,
	"total_boosters_per_hundred" real,
	"new_vaccinations_smoothed_per_million" real,
	"new_people_vaccinated_smoothed" real,
	"new_people_vaccinated_smoothed_per_hundred" real,
	"stringency_index" real,
	"population_density" real,
	"median_age" real,
	"aged_65_older" real,
	"aged_70_older" real,
	"gdp_per_capita" real,
	"extreme_poverty" real,
	"cardiovasc_death_rate" real,
	"diabetes_prevalence" real,
	"female_smokers" real,
	"male_smokers" real,
	"handwashing_facilities" real,
	"hospital_beds_per_thousand" real,
	"life_expectancy" real,
	"human_development_index" real,
	"population" real,
	"excess_mortality_cumulative_absolute" real,
	"excess_mortality_cumulative" real,
	"excess_mortality" real,
	"excess_mortality_cumulative_per_million" real
);
--> statement-breakpoint
CREATE TABLE "projects" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"name" text NOT NULL,
	"description" text,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "todos" (
	"id" serial PRIMARY KEY NOT NULL,
	"user_id" text NOT NULL,
	"project_id" text NOT NULL,
	"title" text NOT NULL,
	"start" text NOT NULL,
	"end" text NOT NULL,
	"duration" real NOT NULL,
	"completed" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
