version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    volumes:
      - aidea:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aidea
    networks:
      - aidea
    ports:
      - "5433:5432"

networks:
  aidea:
    driver: bridge

volumes:
  aidea:
