import { createAsyncThunk, createSlice, PayloadAction } from "@reduxjs/toolkit";
import { RootState } from "../store";
import * as authApi from "./auth.api";
import { User } from "./auth.types";

export interface AuthState {
  isLoadingAuth: boolean;
  authError: string | null;
  loginEmail: string | null;
  user?: User;
}

const initialState: AuthState = {
  isLoadingAuth: true,
  authError: null,
  loginEmail: null,
  user: undefined,
};

export const loadAuth = createAsyncThunk("auth/load", async () => {
  const response = await authApi.getUser();
  return response.data as User;
});

export const logout = createAsyncThunk("auth/logout", authApi.logout);

// We can also write thunks by hand, which may contain both sync and async logic.
// Here's an example of conditionally dispatching actions based on current state.
// export const incrementIfOdd = (amount: number): AppThunk => (
// 	dispatch,
// 	getState,
// ) => {
// 	const user = getUser(getState());
// 	if (!user) {
// 		dispatch(incrementByAmount(amount));
// 	}
// };

const authSlice = createSlice({
  name: "auth",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    setError(state, action: PayloadAction<string | null>) {
      state.authError = action.payload;
    },
    setUser(state, action: PayloadAction<User>) {
      state.user = action.payload;
    },
    setCurrentEmail(state, action: PayloadAction<string | null>) {
      state.loginEmail = action.payload;
    },
  },
  // The `extraReducers` field handles actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(loadAuth.pending, (state) => {
        state.isLoadingAuth = true;
        state.authError = null;
        state.user = undefined;
      })
      .addCase(loadAuth.fulfilled, (state, action) => {
        state.isLoadingAuth = false;
        state.authError = null;
        state.user = action.payload;
      })
      .addCase(loadAuth.rejected, (state, action) => {
        state.isLoadingAuth = false;
        state.authError = action.error.message;
        state.user = undefined;
      })
      .addCase(logout.fulfilled, (state) => {
        state.isLoadingAuth = false;
        state.authError = null;
        state.user = undefined;
      })
      .addCase(logout.rejected, (state, action) => {
        state.isLoadingAuth = false;
        state.authError = action.error.message;
        state.user = undefined;
      });
  },
});

// The function below is called a selector and allows us to select a value from
// the state. Selectors can also be defined inline where they're used instead of
// in the slice file. For example: `useAppSelector((state: RootState) => state.auth.value)`
export const getIsLoadingAuth = (state: RootState) => state.auth.isLoadingAuth;
export const getLoginEmail = (state: RootState) => state.auth.loginEmail;
export const getUser = (state: RootState) => state.auth.user;
export const getIsAuthenticated = (state: RootState) => !!state.auth.user;

export const { setCurrentEmail, setUser } = authSlice.actions;
export default authSlice.reducer;
