name: 🚀 Web > Deploy > Preview

on:
  push:
    branches-ignore:
      - main
    paths: ["apps/web/**", ".github/workflows/deploy-web-preview.yml"]
  workflow_run:
    workflows: ["🔍 Code Quality"]
    types:
      - completed

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 🏗 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Deploy
        run: railway up --service ${{ secrets.RAILWAY_SERVICE_WEB_BETA }}
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}