name: deploy-playground-prod

on:
  push:
    branches: [ main, master ]
    paths:
      - 'apps/playground/**'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - '.github/workflows/deploy-playground-prod.yml'

jobs:
  deploy:
    name: Deploy Playground
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_PLAYGROUND }}
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy to Railway
        run: railway up --service ${{ env.SERVICE_ID }} --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }} 